### ISSUE TITLE
Writing float to TDAC and DAC channels

### ISSUE THREAD

**Issue by Nuthatchary** [bennjii/ljm-rs#4]
Hi there, the write_name function only writes u32, but i need to be able to write a float in order to set DAC channels. Am i missing something?

**Comment by bennjii** [comment]
Good catch, the input parameters say u32, but we only actually require it be converted into a [c_double](https://doc.rust-lang.org/std/os/raw/type.c_double.html), which is simply an alias for the f64 type, so I’ll make the appropriate modifications to support it.

**Comment by bennjii** [comment]
Please confirm this PR addresses your needs. 
To use a branch in a cargo dependency, you can use the following prefix in the entry in `Cargo.toml`:
```toml
ljmrs = { git = "https://github.com/bennjii/ljm-rs.git", branch = "fix/c_double", ... }
```

**Comment by Nuthatchary** [comment]
Thank you so much! I was mostly making sure i wasn't missing something. I appreciate you fixing this!

I also appreciate this repo, I was over the moon when i found it.
