### ISSUE TITLE
Problem with streaming

### ISSUE THREAD

**Issue by domenicnebiker1234** [bennjii/ljm-rs#6]
Hello there, I'm currently trying out streaming mode and noticed that changing the `suggested_scan_rate` parameter changes the size of the returned vector when calling `stream_read`. For example if i want to stream `AIN0,`and `AIN1`, with `scan_per_read = 1` and `suggested_scan_rate = 50`, `stream_read` will return a vector of size `2*50=100`at a frequency of 50Hz. Where only the first two values in the returned vector are different from 0.

**Comment by bennjii** [comment]
Oh I see, I think I’ve located the issue in line 519 of `core.rs`, it should be `scans_per_read` instead of:
```
let mut scan_rate: f64 = suggested_scan_rate;
```
Sorry about that, will resolve soon!

**Comment by bennjii** [comment]
If you want to try out the fix, you can use the specific branch:
```
ljmrs = { git = "https://github.com/bennjii/ljm-rs.git", branch = "fix/stream_size", ... }
```
Let me know if this fixes the issue you're experiencing.

**Comment by domenicnebiker1234** [comment]
Sorry for the late reply, It now kind of most of the time works now but sometimes I still get some random 0.0 values appended to the vector that stream_read returns, do you have any idea if this could be a library issue?

Thanks for the answer

**Comment by bennjii** [comment]
The [LJM docs](https://support.labjack.com/docs/estreamread-ljm-user-s-guide) say that the stream function will block until a full read is complete, then return “ScansPerRead * NumAddresses” values (which is the vector size we allocate). Hinting there should not be trailing 0’s (assuming they aren’t actually valid sensor readings)

A point where this would not be true is if the scans per read is not the same as what was requested, but the docs do not suggest this, or if the number of addresses was somehow not changed correctly between stopping and starting streams. Could you possibly share a reproducible example to help me debug this?

**Comment by domenicnebiker1234** [comment]
I'm using this function to read streams: 
```pub async fn stream(&mut self) -> Result<(), LJError> {
        unsafe { LJM::init() }.ok();

        let data_size = self.sensor_ids.len();

        // handle a possible existing stream
        if LJM::stream_stop(self.handle_id).is_ok() {
            println!("[LJ_STR_{}] Closed existing Stream", self.lj_id);
            tokio::time::sleep(tokio::time::Duration::from_secs(1)).await;
        }

        LJM::stream_start(self.handle_id, 1, self.scan_rate, self.sensor_ports.clone()).map_err(
            |err| {
                LJError::StreamingError(format!(
                    "[LJ_STR_{}] Failed to start stream: {:?}",
                    self.lj_id, err
                ))
            },
        )?;

        loop {
            n_samples += 1;
            let mut values = LJM::stream_read(self.handle_id).map_err(|err| {
                LJError::StreamingError(format!(
                    "[LJ_STR_{}] Failed to read stream: {:?}",
                    self.lj_id, err
                ))
            })?;

           assert_eq!(values.len(), data_size); // this fails sometimes

                for i in 0..data_size {
                    let value = self.sensors[i].convert(values[i]/ n_samples as f64);
                    self.send_data(
                        self.sensor_ids[i].clone(),
                        value,
                    )
                    .await;
                }
            }
        }
    }
```

IF the assertion fails,  it does so right after startup. If the stream has been running for some time it isn't a problem.

**Comment by bennjii** [comment]
I can’t immediately determine the issue, could I have some context as to how `sensor_ports` and `sensor_ids` are defined?

**Comment by domenicnebiker1234** [comment]
sensor_ports are just some AIN# and sensor_ids are just names I gave the sensors in my system. I am using several LabJacks in my system and I thought maybe this is an issue. I am initializing 3-4 labjacks all at once and sometimes it looks like the streaming parameters(ports) get mixed up. this would somewhat explain my issue with the appended zeros. 
E.g. 1 labjack streams 5 ports and another labjack streams 9 ports. if these get mixed up one of them would crash during startup due to a stream size that is not of length of 5 or 9. I am using static IP addresses for the labjacks so I can't really explain why that happens

**Comment by domenicnebiker1234** [comment]
Any updates yet? It still keeps happening sometimes on start up. Sometimes I also get a Heap Corruption. I still think this has something todo with the fact that I'm initializing 3-5 LabJacks at once and it feels like their streaming configs get mixed up due to the wrong size of the returned Vec from stream_read
![Screenshot 2024-11-12 at 12 59 08](https://github.com/user-attachments/assets/71c0ba04-2e58-4977-9f28-f91ac0bbb5fd)

**Comment by bennjii** [comment]
Ah yes, if you're using multiple LabJack streams, it won't work just yet. This is because we have a single state stored for stream internally, so creating a new stream will overwrite this, not create a new one, as this was not within the spec I needed the abstractions for. So, this library does not yet support multiple streams, but I will open a PR soon and add the support, but I may need you to help test it. 

The heap-corruption is caused as the read will expect $Te=S\*L$  where `S=ScansPerRead` and `L=Len(ScanList)`, allocated. But, internally, this library will have allocated $Ti=S_i\*L_i$ where `i` indicates the single stream copy stored internally, which represents the last stream that was started. So, if the stream being read has a larger expected size, `T` than the one set, the LabJack C library will write outside the allocated vector boundary, corrupting the heap (You can read more [here](https://www.twingate.com/blog/glossary/heap%20corruption)).

I'll move this to a new issue.

**Comment by bennjii** [comment]
Moved to https://github.com/bennjii/ljm-rs/issues/9
